services:
  # --- SERVIÇO DO FRONTEND (VUE.JS + NGINX) ---
  frontend:
    build: ./frontend
    container_name: panda-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - panda-net
    depends_on:
      - backend-api

  # --- SERVIÇO DO BACKEND (NODE.JS) ---
  backend-api:
    build: ./Backend
    container_name: panda-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    networks:
      - panda-net
    depends_on:
      mysql-db:
        condition: service_healthy
      redis-cache:
        condition: service_started

  # --- SERVIÇO DO BANCO DE DADOS (MYSQL) ---
  mysql-db:
    image: mysql:8.0
    container_name: panda-mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: guitarra21
      MYSQL_DATABASE: panda
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - panda-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pguitarra21"]
      interval: 10s      
      timeout: 5s        
      retries: 5         
      start_period: 30s  

  # --- SERVIÇO DE CACHE (REDIS) ---
  redis-cache:
    image: 'redis:alpine'
    container_name: panda-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - panda-net

volumes:
  mysql-data:

networks:
  panda-net:
    driver: bridge
